GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA courses TO shsdp_app;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA courses TO shsdp_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA courses
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO shsdp_app;